site_name: Canada Documentation
nav:
  - Home: index.md
  - Geography:
      - Overview: geography/overview.md
      - Provinces and Territories: geography/provinces-territories.md
  - History:
      - Overview: history/overview.md
      - Important Events: history/important-events.md
  - Culture:
      - Overview: culture/overview.md
      - Festivals: culture/festivals.md
  - Finance:
      - Overview: finance/overview.md 
      - Companies: finance/companies.md
  - Economy: economy.md

theme:
  name: material


markdown_extensions:
  - admonition
  - codehilite
  - toc:
      permalink: true

